// src/components/client-side/solid/feedback-wrapper.tsx
// For Solid
/** @jsxImportSource solid-js */

import { For, Show, createResource } from 'solid-js';
import { FeedbackCard } from './feedback-card';

async function fetchFeedback() {
  const response = await fetch('http://localhost:4321/api/feedback.json');

  return response.json();
}

export function FeedbackWrapper() {
  const [feedbacks] = createResource(fetchFeedback);


  return (
    <section class="mt-2 flex flex-col flex-wrap gap-5 h-full w-full">

      <Show when={feedbacks()} fallback={<div>🌀 Fetching information...</div>}>
        <code class='text-sm text-slate-600'>This is a SolidJS component</code>
        <For each={feedbacks().feedback}>
          {(feedback) => (
            <FeedbackCard feedback={feedback} />
          )}
        </For>
      </Show>
    </section >
  );
}

// src/components/client-side/react/feedback-wrapper.tsx
import { Suspense, useEffect, useState } from 'react';
import { FeedbackForm } from './feedback-form';
import { FeedbackList } from './feedback-list';

type Feedbacks = {
  _id: number;
  author: string;
  body: string;
  postedDate: Date;
};

function Loading() {
  return <div>🌀 Fetching information...</div>;
}

export function FeedbackWrapper() {
  const [feedbacks, setFeedbacks] = useState<Feedbacks[]>([]);

  useEffect(() => {
    async function fetchFeedback() {
      try {
        // await new Promise(resolve => {
        //   setTimeout(resolve, 3000);
        // });
        const response = await fetch('/api/feedback.json');
        if (response.ok) {
          const data = await response.json();
          setFeedbacks(data.feedback);
        }

      } catch (error) {
        console.error(error);
      }
    };

    fetchFeedback();
  }, []);

  return (
    <section className="mt-2 flex flex-col flex-wrap gap-5 h-full w-full">
      <code className='text-sm text-slate-600'>This is a client-side component</code>
      <Suspense fallback={<Loading />}>
        <FeedbackList feedbacks={feedbacks} />
      </Suspense>
      <FeedbackForm onSetFeedbacks={setFeedbacks} feedbacks={feedbacks} />
    </section >
  );
}
